// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TagsColumns holds the columns for the "tags" table.
	TagsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Unique: true},
	}
	// TagsTable holds the schema information for the "tags" table.
	TagsTable = &schema.Table{
		Name:       "tags",
		Columns:    TagsColumns,
		PrimaryKey: []*schema.Column{TagsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "age", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VideosColumns holds the columns for the "videos" table.
	VideosColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "url", Type: field.TypeString, Unique: true},
		{Name: "title", Type: field.TypeString},
		{Name: "views", Type: field.TypeInt, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// VideosTable holds the schema information for the "videos" table.
	VideosTable = &schema.Table{
		Name:       "videos",
		Columns:    VideosColumns,
		PrimaryKey: []*schema.Column{VideosColumns[0]},
	}
	// VideoTagsColumns holds the columns for the "video_tags" table.
	VideoTagsColumns = []*schema.Column{
		{Name: "video_id", Type: field.TypeInt},
		{Name: "tag_id", Type: field.TypeInt},
	}
	// VideoTagsTable holds the schema information for the "video_tags" table.
	VideoTagsTable = &schema.Table{
		Name:       "video_tags",
		Columns:    VideoTagsColumns,
		PrimaryKey: []*schema.Column{VideoTagsColumns[0], VideoTagsColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "video_tags_video_id",
				Columns:    []*schema.Column{VideoTagsColumns[0]},
				RefColumns: []*schema.Column{VideosColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "video_tags_tag_id",
				Columns:    []*schema.Column{VideoTagsColumns[1]},
				RefColumns: []*schema.Column{TagsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TagsTable,
		UsersTable,
		VideosTable,
		VideoTagsTable,
	}
)

func init() {
	VideoTagsTable.ForeignKeys[0].RefTable = VideosTable
	VideoTagsTable.ForeignKeys[1].RefTable = TagsTable
}
